### ISSUE TITLE
Layout for question card is not balanced

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#55]
**Describe the bug**
Layout is not balanced when there are questions with different height in a single row

**To Reproduce**
1. Go to https://www.tanyaaja.in/account
2. Check question card

**Expected behavior**

Either we move the button to the very bottom (something like `justify-between` for `flex-col`)

Or make it as we usually call: Mansory Card

**Screenshots**

<img width="1359" alt="Screenshot 2023-10-13 at 11 19 41" src="https://github.com/mazipan/tanyaaja/assets/7221389/0b390486-4f35-45d4-a494-c5145421a798">

**Comment by amarangganar** [comment]
I want to take this one 🙋‍♀️

**Comment by amarangganar** [comment]
If we were to take the masonry layout approach, is it okay to use third-party package? It would be nice if `grid-template-rows: masonry` already supports all browsers but since it hasn't, I don't think it's possible to handle it with pure CSS.

Moving the button to the very bottom is easier though 🤭
